import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fasi
 */
public class appointments extends javax.swing.JFrame {

    /**
     * Creates new form appointments
     */
    public appointments() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int msice = (int) tk.getScreenSize().getWidth();
        int nsice = (int) tk.getScreenSize().getHeight();
        this.setSize(msice, nsice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        idsearch = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        fnamesearch = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        snamesearch = new javax.swing.JTextField();
        datesearch = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        phonesearch = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel72 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        patienttable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        phoneadd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        fnamedelete = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        snamedelete = new javax.swing.JTextField();
        phonedelete = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        iddelete = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        datedelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(51, 204, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("SEARCH APPOINTMENT");
        jLabel55.setOpaque(true);
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel56.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("Date :");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 150, 60));

        jLabel57.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Appointment No :");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 60));

        idsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(idsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        jLabel59.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("First Name :");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 160, 60));

        fnamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(fnamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 200, 40));

        jLabel60.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 255));
        jLabel60.setText("Second Name :");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, 60));

        snamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(snamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 200, 40));

        datesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(datesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 200, 40));

        jLabel67.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 102, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("Phone no.");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 160, 60));

        phonesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(phonesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, 40));

        jLabel68.setIcon(new javax.swing.ImageIcon("E:\\IP PROJECT (2019-2020)\\HospitalMangementSystem\\src\\download_6_250x240.png")); // NOI18N
        jLabel68.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel72.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton12.setBackground(new java.awt.Color(51, 153, 255));
        jButton12.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("SEARCH");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 50));

        jTabbedPane1.addTab("Search Appointment", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setBackground(new java.awt.Color(51, 204, 255));
        jLabel73.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel73.setText("VIEW APPOINTMENTS");
        jLabel73.setOpaque(true);
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel74.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel5.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retrive Data from Database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 400, 50));

        patienttable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patienttable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientId", "FirstName", "SecondName", "Date", "Phoneno"
            }
        ));
        jScrollPane2.setViewportView(patienttable1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1350, 460));

        jTabbedPane1.addTab("View Appointment", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("CREATE APPOINTMENT");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Phone no :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 150, 60));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Appointment No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 60));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 200, 40));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("First Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Second Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 180, 60));

        sname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 200, 40));

        phoneadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(phoneadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 200, 40));

        jLabel15.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CREATE APPOINTMENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 290, 76));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 150, 60));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 200, 40));

        jTabbedPane1.addTab("Add Appointment", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("DELETE APPOINTMENT");
        jLabel37.setOpaque(true);
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel38.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Phone no : ");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 150, 60));

        jLabel39.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Appointment No :");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 60));

        jLabel41.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("First Name :");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 160, 60));

        fnamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(fnamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 200, 40));

        jLabel42.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 255));
        jLabel42.setText("Second Name :");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 180, 60));

        snamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(snamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 200, 40));

        phonedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phonedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 200, 40));

        jLabel50.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel50.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel54.setIcon(new javax.swing.ImageIcon("E:\\IP PROJECT (2019-2020)\\HospitalMangementSystem\\images used in IP Project\\download_2_3_70x60.png")); // NOI18N
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton10.setBackground(new java.awt.Color(51, 153, 255));
        jButton10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("DELETE APPOINTMENT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 290, 76));

        iddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddeleteActionPerformed(evt);
            }
        });
        jPanel2.add(iddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 200, 40));

        jButton9.setBackground(new java.awt.Color(51, 153, 255));
        jButton9.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SEARCH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jLabel58.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setText("Date :");
        jPanel2.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 150, 60));

        datedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datedelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datedeleteActionPerformed(evt);
            }
        });
        jPanel2.add(datedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, 40));

        jTabbedPane1.addTab("Delete Appointment", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String sql = "select * from appointments where Appointmentno=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, iddelete.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamedelete.setText(resultSet.getString("FirstName"));
                snamedelete.setText(resultSet.getString("SecondName"));
                datedelete.setText(resultSet.getString("Date"));
                phonedelete.setText(resultSet.getString("Phoneno"));
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void iddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddeleteActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection  con=DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","wysiwygmik");
            Statement  stmt=con.createStatement();
            String query="delete from appointments where Appointmentno="+iddelete.getText()+";";
            stmt.executeUpdate(query);
            stmt.close();
            con.close();
            JOptionPane.showMessageDialog(this,"Record Deleted successfully");
            iddelete.setText("");
            fnamedelete.setText("");
            snamedelete.setText("");
            phonedelete.setText("");
            datedelete.setText("");
       }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String appointmentno = id.getText();
        String firstname = fname.getText();
        String secondname = sname.getText();
        String datee = (String) date.getText();
        String phone = phoneadd.getText();
        if (appointmentno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Patient ID not entered");
        } else if (firstname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name not entered");
        } else if (secondname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Second Name not entered");
        } else if (datee.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date not entered");}
            else {
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO appointments VALUES ('" + appointmentno + "','" + firstname + "','" + secondname + "','" + phone + "','" +datee+"');";
                stmt.executeUpdate(query);
                id.setText("");
                fname.setText("");
                sname.setText("");
                phoneadd.setText("");
                date.setText("");
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(this,"Record Inserted successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) patienttable1.getModel();
        model.setNumRows(0);
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            Statement stmt = con.createStatement();
            String Tname = "appointments";
            String query = "select * from " + Tname + ";";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String id = rs.getString("Appointmentno");
                String firstname = rs.getString("FirstName");
                String secondname = rs.getString("SecondName");
                String Datee = rs.getString("Date");
                long phoneno = rs.getLong("Phoneno");
                
                model.addRow(new Object[]{id, firstname, secondname, Datee,phoneno,});
            }
            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String sql = "select * from appointments where Appointmentno=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idsearch.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamesearch.setText(resultSet.getString("FirstName"));
                snamesearch.setText(resultSet.getString("SecondName"));
                datesearch.setText(resultSet.getString("Date"));
                phonesearch.setText(resultSet.getString("Phoneno"));
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void datedeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datedeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datedeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new Receptionistportal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appointments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appointments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField date;
    private javax.swing.JTextField datedelete;
    private javax.swing.JTextField datesearch;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fnamedelete;
    private javax.swing.JTextField fnamesearch;
    private javax.swing.JTextField id;
    private javax.swing.JTextField iddelete;
    private javax.swing.JTextField idsearch;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable patienttable1;
    private javax.swing.JTextField phoneadd;
    private javax.swing.JTextField phonedelete;
    private javax.swing.JTextField phonesearch;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField snamedelete;
    private javax.swing.JTextField snamesearch;
    // End of variables declaration//GEN-END:variables
}
