
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;

/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fasi
 */
public class Patientdetails extends javax.swing.JFrame {

    /**
     * Creates new form Patientdetails
     */
    public Patientdetails() {
        initComponents();
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        Toolkit tk = Toolkit.getDefaultToolkit();
        int msice = (int) tk.getScreenSize().getWidth();
        int nsice = (int) tk.getScreenSize().getHeight();
        this.setSize(msice, nsice);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        bedsearch = new javax.swing.JTextField();
        idsearch = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        placesearch = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        fnamesearch = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        relationsearch = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        typesearch = new javax.swing.JComboBox<>();
        jLabel62 = new javax.swing.JLabel();
        snamesearch = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        wardsearch = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        agesearch = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        datesearch = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        worksearch = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        phonesearch = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        cityysearch = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        gensearch = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton12 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bedupdate = new javax.swing.JTextField();
        idupdate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        placeupdate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fnameupdate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        relationupdate = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        typeupdate = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        snameupdate = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        wardupdate = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ageupdate = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        dateupdate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        workupdate = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        phoneupdate = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cityyupdate = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        genupdate = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        patienttable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bed = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        place = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        relation = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        typee = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ward = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        work = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cityy = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        gen = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        beddelete = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        placedelete = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        fnamedelete = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        relationdelete = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        typedelete = new javax.swing.JComboBox<>();
        jLabel44 = new javax.swing.JLabel();
        snamedelete = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        warddelete = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        agedelete = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        datedelete = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        workdelete = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        phonedelete = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cityydelete = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        gendelete = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        iddelete = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(51, 204, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("SEARCH PATIENT");
        jLabel55.setOpaque(true);
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel56.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("Date :");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel57.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Patient ID :");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 60));

        bedsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(bedsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 200, 40));

        idsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(idsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        jLabel58.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(0, 102, 255));
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel58.setText("Bed no.");
        jPanel3.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 160, 60));

        placesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(placesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel59.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("First Name :");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(fnamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel60.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 255));
        jLabel60.setText("Second Name :");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationsearch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel3.add(relationsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel61.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Age :");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        typesearch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        typesearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor" }));
        jPanel3.add(typesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 200, 30));

        jLabel62.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel62.setText("Gender :");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(snamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel63.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 102, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Marital Status :");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        wardsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(wardsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 200, 40));

        jLabel64.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 102, 255));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("Address :");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        agesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(agesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel65.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 102, 255));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setText("Ward no.");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 160, 60));

        datesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(datesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel66.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 102, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("Patient Type :");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        worksearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(worksearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel67.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 102, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("Phone no.");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        phonesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(phonesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jLabel68.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel68.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel69.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 102, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("City :");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityysearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(cityysearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        jLabel70.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(0, 102, 255));
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel70.setText("[ For Indoor Patients Only ]");
        jPanel3.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 770, 60));

        gensearch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        gensearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(gensearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel71.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 102, 255));
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("Occupation :");
        jPanel3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        jLabel72.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton12.setBackground(new java.awt.Color(51, 153, 255));
        jButton12.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("SEARCH");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 420, 250, 70));

        jTabbedPane1.addTab("Search Patient", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(51, 204, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("UPDATE PATIENT");
        jLabel19.setOpaque(true);
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Date :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Patient ID :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 60));

        bedupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(bedupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 200, 40));

        idupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(idupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        jLabel22.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Bed no.");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 160, 60));

        placeupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(placeupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("First Name :");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnameupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(fnameupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel24.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 255));
        jLabel24.setText("Second Name :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel4.add(relationupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel25.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Age :");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        typeupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        typeupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor" }));
        jPanel4.add(typeupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 200, 30));

        jLabel26.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Gender :");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snameupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(snameupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel27.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Marital Status :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        wardupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wardupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wardupdateActionPerformed(evt);
            }
        });
        jPanel4.add(wardupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 200, 40));

        jLabel28.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Address :");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        ageupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(ageupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel29.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Ward no.");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 160, 60));
        jPanel4.add(dateupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel30.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Patient Type :");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        workupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(workupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel31.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Phone no.");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        phoneupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(phoneupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jLabel32.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel32.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel33.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("City :");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityyupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(cityyupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        jLabel34.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("[ For Indoor Patients Only ]");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 770, 60));

        genupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        genupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel4.add(genupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel35.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Occupation :");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE PATIENT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 76));

        jLabel36.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton11.setBackground(new java.awt.Color(51, 153, 255));
        jButton11.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("SEARCH");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jTabbedPane1.addTab("Update Patient", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setBackground(new java.awt.Color(51, 204, 255));
        jLabel73.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel73.setText("VIEW PATIENTS");
        jLabel73.setOpaque(true);
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel74.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel5.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retrive Data from Database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 590, 400, 50));

        patienttable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patienttable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PatientId", "FirstName", "SecondName", "Age", "Gender", "MaritalStatus", "DateOfAdmit", "Address", "City", "Phoneno", "Occupation", "Type", "Wardno", "Bedno"
            }
        ));
        jScrollPane2.setViewportView(patienttable1);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1350, 460));

        jTabbedPane1.addTab("View Patients", jPanel5);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ADD PATIENT");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Patient ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 60));

        bed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(bed, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 200, 40));

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Bed no.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 160, 60));

        place.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(place, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("First Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Second Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relation.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel1.add(relation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Age :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        typee.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        typee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor" }));
        jPanel1.add(typee, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 200, 30));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        sname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Marital Status :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        ward.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ward, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 200, 40));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Address :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        age.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Ward no.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 160, 60));

        date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Patient Type :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        work.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(work, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Phone no.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        phone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jLabel15.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("City :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(cityy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("[ For Indoor Patients Only ]");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 770, 60));

        gen.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(gen, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Occupation :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD PATIENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 76));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jTabbedPane1.addTab("Add Patient", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("DELETE PATIENT");
        jLabel37.setOpaque(true);
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel38.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Date :");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel39.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Patient ID :");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 160, 60));

        beddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(beddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 200, 40));

        jLabel40.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 255));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Bed no.");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 160, 60));

        placedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(placedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel41.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("First Name :");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(fnamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel42.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 255));
        jLabel42.setText("Second Name :");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationdelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationdelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel2.add(relationdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel43.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Age :");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        typedelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        typedelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indoor", "Outdoor" }));
        jPanel2.add(typedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 200, 30));

        jLabel44.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Gender :");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(snamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel45.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Marital Status :");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        warddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(warddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 200, 40));

        jLabel46.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Address :");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        agedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(agedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel47.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Ward no.");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 160, 60));

        datedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(datedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel48.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 102, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("Patient Type :");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        workdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(workdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel49.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 102, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Phone no.");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        phonedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phonedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jLabel50.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel50.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel51.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 102, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("City :");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityydelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cityydelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        jLabel52.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 102, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("[ For Indoor Patients Only ]");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 770, 60));

        gendelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        gendelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(gendelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel53.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 102, 255));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel53.setText("Occupation :");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        jLabel54.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton10.setBackground(new java.awt.Color(51, 153, 255));
        jButton10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("DELETE PATIENT");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 76));

        iddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iddelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddeleteActionPerformed(evt);
            }
        });
        jPanel2.add(iddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        jButton9.setBackground(new java.awt.Color(51, 153, 255));
        jButton9.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SEARCH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jTabbedPane1.addTab("Delete Patient", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String patientid = id.getText();
        String firstname = fname.getText();
        String secondname = sname.getText();
        String agee = age.getText();
        String address = place.getText();
        String city = cityy.getText();
        String phoneno = phone.getText();
        String occupation = work.getText();
        String wardno = ward.getText();
        String bedno = bed.getText();
        String gender = (String) gen.getSelectedItem();
        String marriage = (String) relation.getSelectedItem();
        String patienttype = (String) typee.getSelectedItem();
        String datee = (String) date.getText();
        if (patientid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Patient ID not entered");
        } else if (firstname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name not entered");
        } else if (secondname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Second Name not entered");
        } else if (agee.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Age not entered");
        } else if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address not entered");
        } else if (city.isEmpty()) {
            JOptionPane.showMessageDialog(this, "City not entered");
        } else if (phoneno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number not entered");
        } else if (occupation.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Occupation not entered");
        } else if (wardno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ward Number not entered");
        } else if (bedno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "bed number not entered");
        } else {
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO PatientDetails VALUES ('" + patientid + "','" + firstname + "','" + secondname + "','" + agee + "','" + address + "','" + city + "','" + phoneno + "','" + occupation + "','" + wardno + "','" + bedno + "','" + gender + "','" + marriage + "','" + patienttype +"','"+datee+"');";
                stmt.executeUpdate(query);
                id.setText("");
                fname.setText("");
                sname.setText("");
                age.setText("");
                place.setText("");
                cityy.setText("");
                phone.setText("");
                work.setText("");
                ward.setText("");
                bed.setText("");
                date.setText("");
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(this,"Record Inserted successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            String sql = "UPDATE PatientDetails SET FirstName=?,SecondName=?,age=?,Address=?,City=?,Phoneno=?,Occupation=?,Wardno=?,Bedno=?,Gender=?,MaritalStatus=?,PatientType=?,DateofAdmit=? WHERE PatientId=?";
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(14, idupdate.getText());
            ps.setString(1,fnameupdate.getText());
            ps.setString(2,snameupdate.getText());
            ps.setString(3,ageupdate.getText());
            ps.setString(4,placeupdate.getText());
            ps.setString(5, cityyupdate.getText());
            ps.setString(6,phoneupdate.getText());
            ps.setString(7,workupdate.getText());
            ps.setString(8,wardupdate.getText());
            ps.setString(9, bedupdate.getText());
            ps.setString(10, (String) genupdate.getSelectedItem());
            ps.setString(11, (String) relationupdate.getSelectedItem());
            ps.setString(12, (String) typeupdate.getSelectedItem());
            ps.setString(13, dateupdate.getText());
            
            ps.executeUpdate();
          JOptionPane.showMessageDialog(this,"Record Updated Successfully");
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
try
        {
        Class.forName("java.sql.Driver");
        Connection  con=DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","wysiwygmik");  
        Statement  stmt=con.createStatement();
        String query="delete from patientdetails where PatientId="+iddelete.getText()+";";
        stmt.executeUpdate(query);
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(this,"Record Deleted successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton10ActionPerformed
    
    
    
    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
 String sql = "select * from Patientdetails where PatientId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idupdate.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnameupdate.setText(resultSet.getString("FirstName"));
                snameupdate.setText(resultSet.getString("SecondName"));
                ageupdate.setText(resultSet.getString("Age"));
                genupdate.setSelectedItem(resultSet.getString("Gender"));
                relationupdate.setSelectedItem(resultSet.getString("MaritalStatus"));
                dateupdate.setText(resultSet.getString("DateOfAdmit"));
                placeupdate.setText(resultSet.getString("Address"));
                cityyupdate.setText(resultSet.getString("City"));
                phoneupdate.setText(resultSet.getString("Phoneno"));
                workupdate.setText(resultSet.getString("Occupation"));
                typeupdate.setSelectedItem(resultSet.getString("PatientType"));
                wardupdate.setText(resultSet.getString("Wardno"));
                bedupdate.setText(resultSet.getString("Bedno"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
String sql = "select * from Patientdetails where PatientId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idsearch.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamesearch.setText(resultSet.getString("FirstName"));
                snamesearch.setText(resultSet.getString("SecondName"));
                agesearch.setText(resultSet.getString("Age"));
                gensearch.setSelectedItem(resultSet.getString("Gender"));
                relationsearch.setSelectedItem(resultSet.getString("MaritalStatus"));
                datesearch.setText(resultSet.getString("DateOfAdmit"));
                placesearch.setText(resultSet.getString("Address"));
                cityysearch.setText(resultSet.getString("City"));
                phonesearch.setText(resultSet.getString("Phoneno"));
                worksearch.setText(resultSet.getString("Occupation"));
                typesearch.setSelectedItem(resultSet.getString("PatientType"));
                wardsearch.setText(resultSet.getString("Wardno"));
                bedsearch.setText(resultSet.getString("Bedno"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
DefaultTableModel model = (DefaultTableModel) patienttable1.getModel();
        model.setNumRows(0);
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            Statement stmt = con.createStatement();
            String Tname = "Patientdetails";
            String query = "select * from " + Tname + ";";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String id = rs.getString("PatientId");
                String firstname = rs.getString("FirstName");
                String secondname = rs.getString("SecondName");
                int age = rs.getInt("Age");
                String gender = rs.getString("Gender");
                String marry = rs.getString("MaritalStatus");
                String Datee = rs.getString("DateOfAdmit");
                String address = rs.getString("Address");
                String city = rs.getString("City");
                long phoneno = rs.getLong("Phoneno");
                String occupation = rs.getString("Occupation");
                String type = rs.getString("PatientType");
                int wardno = rs.getInt("Wardno");
                int bedno = rs.getInt("Bedno");

                model.addRow(new Object[]{id, firstname, secondname, age, gender, marry, Datee, address, city, phoneno, occupation, type, wardno, bedno});
            }
            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iddeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddeleteActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
String sql = "select * from Patientdetails where PatientId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, iddelete.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamedelete.setText(resultSet.getString("FirstName"));
                snamedelete.setText(resultSet.getString("SecondName"));
                agedelete.setText(resultSet.getString("Age"));
                gendelete.setSelectedItem(resultSet.getString("Gender"));
                relationdelete.setSelectedItem(resultSet.getString("MaritalStatus"));
                datedelete.setText(resultSet.getString("DateOfAdmit"));
                placedelete.setText(resultSet.getString("Address"));
                cityydelete.setText(resultSet.getString("City"));
                phonedelete.setText(resultSet.getString("Phoneno"));
                workdelete.setText(resultSet.getString("Occupation"));
                typedelete.setSelectedItem(resultSet.getString("PatientType"));
                warddelete.setText(resultSet.getString("Wardno"));
                beddelete.setText(resultSet.getString("Bedno"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void wardupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wardupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wardupdateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Adminportal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patientdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patientdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patientdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patientdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patientdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField agedelete;
    private javax.swing.JTextField agesearch;
    private javax.swing.JTextField ageupdate;
    private javax.swing.JTextField bed;
    private javax.swing.JTextField beddelete;
    private javax.swing.JTextField bedsearch;
    private javax.swing.JTextField bedupdate;
    private javax.swing.JTextField cityy;
    private javax.swing.JTextField cityydelete;
    private javax.swing.JTextField cityysearch;
    private javax.swing.JTextField cityyupdate;
    private javax.swing.JTextField date;
    private javax.swing.JTextField datedelete;
    private javax.swing.JTextField datesearch;
    private javax.swing.JTextField dateupdate;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fnamedelete;
    private javax.swing.JTextField fnamesearch;
    private javax.swing.JTextField fnameupdate;
    private javax.swing.JComboBox<String> gen;
    private javax.swing.JComboBox<String> gendelete;
    private javax.swing.JComboBox<String> gensearch;
    private javax.swing.JComboBox<String> genupdate;
    private javax.swing.JTextField id;
    private javax.swing.JTextField iddelete;
    private javax.swing.JTextField idsearch;
    private javax.swing.JTextField idupdate;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable patienttable1;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField phonedelete;
    private javax.swing.JTextField phonesearch;
    private javax.swing.JTextField phoneupdate;
    private javax.swing.JTextField place;
    private javax.swing.JTextField placedelete;
    private javax.swing.JTextField placesearch;
    private javax.swing.JTextField placeupdate;
    private javax.swing.JComboBox<String> relation;
    private javax.swing.JComboBox<String> relationdelete;
    private javax.swing.JComboBox<String> relationsearch;
    private javax.swing.JComboBox<String> relationupdate;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField snamedelete;
    private javax.swing.JTextField snamesearch;
    private javax.swing.JTextField snameupdate;
    private javax.swing.JComboBox<String> typedelete;
    private javax.swing.JComboBox<String> typee;
    private javax.swing.JComboBox<String> typesearch;
    private javax.swing.JComboBox<String> typeupdate;
    private javax.swing.JTextField ward;
    private javax.swing.JTextField warddelete;
    private javax.swing.JTextField wardsearch;
    private javax.swing.JTextField wardupdate;
    private javax.swing.JTextField work;
    private javax.swing.JTextField workdelete;
    private javax.swing.JTextField worksearch;
    private javax.swing.JTextField workupdate;
    // End of variables declaration//GEN-END:variables
}
