import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fasi
 */
public class Receptionistdetails extends javax.swing.JFrame {

    /**
     * Creates new form Receptionistdetails
     */
    public Receptionistdetails() {
          this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int msice = (int) tk.getScreenSize().getWidth();
        int nsice = (int) tk.getScreenSize().getHeight();
        this.setSize(msice, nsice);
        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        idsearch = new javax.swing.JTextField();
        addresssearch = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        fnamesearch = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        relationsearch = new javax.swing.JComboBox<>();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        snamesearch = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        joinsearch = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        agesearch = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        datesearch = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        bloodsearch = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        cityysearch = new javax.swing.JTextField();
        gensearch = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel72 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        phonenosearch = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idupdate = new javax.swing.JTextField();
        addressupdate = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fnameupdate = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        relationupdate = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        snameupdate = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        joinupdate = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ageupdate = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        dateupdate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        bloodupdate = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cityyupdate = new javax.swing.JTextField();
        genupdate = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        phonenoupdate = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        receptable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        iddelete = new javax.swing.JTextField();
        addressdelete = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        fnamedelete = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        relationdelete = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        snamedelete = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        joindelete = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        agedelete = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        datedelete = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        blooddelete = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        cityydelete = new javax.swing.JTextField();
        gendelete = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        phonenodelete = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idadd = new javax.swing.JTextField();
        addressadd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fnameadd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        relationadd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        snameadd = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        joinadd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ageadd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dateadd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bloodadd = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cityyadd = new javax.swing.JTextField();
        genadd = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        phonenoadd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel55.setBackground(new java.awt.Color(51, 204, 255));
        jLabel55.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel55.setText("SEARCH RECEPTIONIST");
        jLabel55.setOpaque(true);
        jPanel3.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel56.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 102, 255));
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel56.setText("Date :");
        jPanel3.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel57.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 102, 255));
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Receptionist ID :");
        jPanel3.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 60));

        idsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(idsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        addresssearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(addresssearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel59.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(0, 102, 255));
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("First Name :");
        jPanel3.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(fnamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel60.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 255));
        jLabel60.setText("Second Name :");
        jPanel3.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationsearch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationsearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel3.add(relationsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel61.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(0, 102, 255));
        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Age :");
        jPanel3.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        jLabel62.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(0, 102, 255));
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel62.setText("Gender :");
        jPanel3.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snamesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(snamesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel63.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(0, 102, 255));
        jLabel63.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel63.setText("Marital Status :");
        jPanel3.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        joinsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(joinsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel64.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(0, 102, 255));
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel64.setText("Address :");
        jPanel3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        agesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(agesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel65.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(0, 102, 255));
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setText("Join Date :");
        jPanel3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        datesearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(datesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel66.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(0, 102, 255));
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("Blood Group :");
        jPanel3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        jLabel67.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(0, 102, 255));
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("Phone no.");
        jPanel3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        bloodsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(bloodsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 200, 40));

        jLabel68.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel68.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel3.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel69.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(0, 102, 255));
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("City :");
        jPanel3.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityysearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(cityysearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        gensearch.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        gensearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(gensearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jLabel72.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton9.setBackground(new java.awt.Color(51, 153, 255));
        jButton9.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("SEARCH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        phonenosearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(phonenosearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jButton8.setBackground(new java.awt.Color(51, 153, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 250, 80));

        jTabbedPane1.addTab("Search Receptionist", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(51, 204, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("UPDATE RECEPTIONIST");
        jLabel19.setOpaque(true);
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 102, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Date :");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel21.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Receptionist ID :");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 60));

        idupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(idupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        addressupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(addressupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("First Name :");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnameupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(fnameupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel24.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 255));
        jLabel24.setText("Second Name :");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        relationupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationupdateActionPerformed(evt);
            }
        });
        jPanel4.add(relationupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel25.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 102, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Age :");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        jLabel26.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Gender :");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snameupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        snameupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameupdateActionPerformed(evt);
            }
        });
        jPanel4.add(snameupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel27.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Marital Status :");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        joinupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(joinupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel28.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Address :");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        ageupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(ageupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel29.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 102, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel29.setText("Join Date :");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        dateupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(dateupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel30.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Blood Group");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        jLabel31.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel31.setText("Phone no.");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        bloodupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(bloodupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 200, 40));

        jLabel32.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel32.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel33.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("City :");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityyupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(cityyupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        genupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        genupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel4.add(genupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE RECEPTIONIST");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 400, 280, 76));

        jLabel36.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton7.setBackground(new java.awt.Color(51, 153, 255));
        jButton7.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        phonenoupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(phonenoupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jTabbedPane1.addTab("Update Receptionist", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setBackground(new java.awt.Color(51, 204, 255));
        jLabel73.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel73.setText("VIEW RECEPTIONISTS");
        jLabel73.setOpaque(true);
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel74.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel5.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        receptable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        receptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RecepId", "FirstName", "SecondName", "Age", "Gender", "MaritalStatus", "DateOfBirth", "Address", "City", "Phoneno", "Blood Group", "Join Date"
            }
        ));
        jScrollPane2.setViewportView(receptable);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1350, 440));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retrive Data from Database");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 570, 400, 50));

        jTabbedPane1.addTab("View Receptionists", jPanel5);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setBackground(new java.awt.Color(51, 204, 255));
        jLabel37.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("DELETE RECEPTIONIST");
        jLabel37.setOpaque(true);
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel38.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Date :");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel39.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 255));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText(" Receptionist ID :");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 260, 60));

        iddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(iddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        addressdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(addressdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel41.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 255));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("First Name :");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(fnamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel42.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 255));
        jLabel42.setText("Second Name :");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationdelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationdelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel2.add(relationdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel43.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 255));
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Age :");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        jLabel44.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 255));
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Gender :");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snamedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(snamedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel45.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 102, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Marital Status :");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        joindelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(joindelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel46.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 102, 255));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel46.setText("Address :");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        agedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(agedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel47.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 255));
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel47.setText("Join Date :");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        datedelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(datedelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel48.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 102, 255));
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel48.setText("Blood Group :");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        jLabel49.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 102, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Phone no.");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        blooddelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(blooddelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 200, 40));

        jLabel50.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel50.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel51.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 102, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("City :");
        jPanel2.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityydelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(cityydelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        gendelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        gendelete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(gendelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        jButton5.setBackground(new java.awt.Color(51, 153, 255));
        jButton5.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 200, 50));

        jLabel54.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 870, 30));

        jButton6.setBackground(new java.awt.Color(51, 153, 255));
        jButton6.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("DELETE RECEPTIONIST");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 400, 290, 76));

        phonenodelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(phonenodelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jTabbedPane1.addTab("Delete Receptionist", jPanel2);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ADD RECEPTIONIST");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 1310, 60));

        jLabel3.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_2_3_70x60.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 70, 60));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 150, 60));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Receptionist ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 210, 60));

        idadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(idadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 200, 40));

        addressadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(addressadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 630, 40));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("First Name :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 60));

        fnameadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fnameadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 40));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 255));
        jLabel7.setText("Second Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 180, 60));

        relationadd.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        relationadd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel1.add(relationadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 306, 200, 30));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Age :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 160, 60));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Gender :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 150, 60));

        snameadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(snameadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 200, 40));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Marital Status :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 60));

        joinadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(joinadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 200, 40));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Address :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 160, 60));

        ageadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ageadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 200, 40));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Join Date :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 160, 60));

        dateadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(dateadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, 40));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Blood Group :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 160, 60));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Phone no.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 160, 60));

        bloodadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(bloodadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 200, 40));

        jLabel15.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/IP PROJECT (2019-2020)/HospitalMangementSystem/src/download_6_250x240.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 204, 255)));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 250, 240));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("City :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 160, 60));

        cityyadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(cityyadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 40));

        genadd.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        genadd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(genadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 200, -1));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD RECEPTIONIST");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 250, 76));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 870, 30));

        phonenoadd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(phonenoadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 200, 40));

        jTabbedPane1.addTab("Add Receptionists", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
String sql = "select * from ReceptionistDetails where RecepId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idsearch.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamesearch.setText(resultSet.getString("FirstName"));
                snamesearch.setText(resultSet.getString("SecondName"));
                agesearch.setText(resultSet.getString("Age"));
                gensearch.setSelectedItem(resultSet.getString("Gender"));
                relationsearch.setSelectedItem(resultSet.getString("MaritalStatus"));
                datesearch.setText(resultSet.getString("DateOfBirth"));
                addresssearch.setText(resultSet.getString("Address"));
                cityysearch.setText(resultSet.getString("City"));
                phonenosearch.setText(resultSet.getString("Phoneno"));
                joinsearch.setText(resultSet.getString("JoinDate"));
                bloodsearch.setText(resultSet.getString("BloodGroup"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
            String sql = "UPDATE ReceptionistDetails SET FirstName=?,SecondName=?,age=?,Gender=?,MaritalStatus=?,DateofBirth=?,Address=?,City=?,Phoneno=?,BloodGroup=?,JoinDate=? WHERE RecepId=?";
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(12, idupdate.getText());
            ps.setString(1,fnameupdate.getText());
            ps.setString(2,snameupdate.getText());
            ps.setString(3,ageupdate.getText());
            ps.setString(4, (String) genupdate.getSelectedItem());
            ps.setString(5, (String) relationupdate.getSelectedItem());
            ps.setString(6,dateupdate.getText());
            ps.setString(7,addressupdate.getText());
            ps.setString(8,cityyupdate.getText());
            ps.setString(9, phonenoupdate.getText());
            ps.setString(10,bloodupdate.getText());
            ps.setString(11,joinupdate.getText());
            ps.executeUpdate();
          JOptionPane.showMessageDialog(this,"Record Updated Successfully");
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
String sql = "select * from ReceptionistDetails where RecepId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idupdate.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnameupdate.setText(resultSet.getString("FirstName"));
                snameupdate.setText(resultSet.getString("SecondName"));
                ageupdate.setText(resultSet.getString("Age"));
                genupdate.setSelectedItem(resultSet.getString("Gender"));
                relationupdate.setSelectedItem(resultSet.getString("MaritalStatus"));
                dateupdate.setText(resultSet.getString("DateOfBirth"));
                addressupdate.setText(resultSet.getString("Address"));
                cityyupdate.setText(resultSet.getString("City"));
                phonenoupdate.setText(resultSet.getString("Phoneno"));
                joinupdate.setText(resultSet.getString("JoinDate"));
                bloodupdate.setText(resultSet.getString("BloodGroup"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String recepid = idadd.getText();
        String firstname = fnameadd.getText();
        String secondname = snameadd.getText();
        String agee = ageadd.getText();
        String address = addressadd.getText();
        String city = cityyadd.getText();
        String phoneno = phonenoadd.getText();
        String join = joinadd.getText();
        String group = bloodadd.getText();
        String gender = (String) genadd.getSelectedItem();
        String marriage = (String) relationadd.getSelectedItem();
        String datee = (String) dateadd.getText();
        if (recepid.isEmpty()) {
            JOptionPane.showMessageDialog(this, "DoctorId not entered");
        } else if (firstname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "First name not entered");
        } else if (secondname.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Second Name not entered");
        } else if (agee.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Age not entered");
        } else if (address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address not entered");
        } else if (city.isEmpty()) {
            JOptionPane.showMessageDialog(this, "City not entered");
        } else if (phoneno.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number not entered");
        } else if (join.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Join Date not entered");
        } else if (group.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Blood Group not entered");
        } else if (datee.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date Of Birth not entered");
        }else {
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO ReceptionistDetails VALUES ('" + recepid + "','" + firstname + "','" + secondname + "','" + agee + "','" + gender + "','" + marriage + "','" + datee + "','" + address + "','" + city + "','" + phoneno + "','" + group + "','" +join+"');";
                stmt.executeUpdate(query);
                idadd.setText("");
                fnameadd.setText("");
                snameadd.setText("");
                ageadd.setText("");
                addressadd.setText("");
                cityyadd.setText("");
                phonenoadd.setText("");
                joinadd.setText("");
                bloodadd.setText("");
                dateadd.setText("");
                stmt.close();
                con.close();
                JOptionPane.showMessageDialog(this, "Record Inserted Successfully");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String sql = "select * from ReceptionistDetails where RecepId=?";
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, iddelete.getText());
            ResultSet resultSet;
            resultSet = ps.executeQuery();
            if (resultSet.next()) {
                fnamedelete.setText(resultSet.getString("FirstName"));
                snamedelete.setText(resultSet.getString("SecondName"));
                agedelete.setText(resultSet.getString("Age"));
                gendelete.setSelectedItem(resultSet.getString("Gender"));
                relationdelete.setSelectedItem(resultSet.getString("MaritalStatus"));
                datedelete.setText(resultSet.getString("DateOfBirth"));
                addressdelete.setText(resultSet.getString("Address"));
                cityydelete.setText(resultSet.getString("City"));
                phonenodelete.setText(resultSet.getString("Phoneno"));
                joindelete.setText(resultSet.getString("JoinDate"));
                blooddelete.setText(resultSet.getString("BloodGroup"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
try
        {
        Class.forName("java.sql.Driver");
        Connection  con=DriverManager.getConnection("jdbc:mysql://localhost/hospital","root","wysiwygmik");  
        Statement  stmt=con.createStatement();
        String query="delete from ReceptionistDetails where RecepId="+iddelete.getText()+";";
        stmt.executeUpdate(query);
        stmt.close();
        con.close();
        JOptionPane.showMessageDialog(this,"Record Deleted Successfully");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) receptable.getModel();
        model.setNumRows(0);
        try {
            Class.forName("java.sql.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "wysiwygmik");
            Statement stmt = con.createStatement();
            String Tname = "ReceptionistDetails";
            String query = "select * from " + Tname + ";";
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()) {
                String id = rs.getString("RecepId");
                String firstname = rs.getString("FirstName");
                String secondname = rs.getString("SecondName");
                int age = rs.getInt("Age");
                String gender = rs.getString("Gender");
                String marry = rs.getString("MaritalStatus");
                String Datee = rs.getString("DateOfBirth");
                String address = rs.getString("Address");
                String city = rs.getString("City");
                long phoneno = rs.getLong("Phoneno");
                String group = rs.getString("BloodGroup");
                String join = rs.getString("JoinDate");

                model.addRow(new Object[]{id, firstname, secondname, age, gender, marry, Datee, address, city, phoneno,group, join});
            }
            rs.close();
            stmt.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void snameupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameupdateActionPerformed

    private void relationupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationupdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationupdateActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new Adminportal().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionistdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionistdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionistdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionistdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionistdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressadd;
    private javax.swing.JTextField addressdelete;
    private javax.swing.JTextField addresssearch;
    private javax.swing.JTextField addressupdate;
    private javax.swing.JTextField ageadd;
    private javax.swing.JTextField agedelete;
    private javax.swing.JTextField agesearch;
    private javax.swing.JTextField ageupdate;
    private javax.swing.JTextField bloodadd;
    private javax.swing.JTextField blooddelete;
    private javax.swing.JTextField bloodsearch;
    private javax.swing.JTextField bloodupdate;
    private javax.swing.JTextField cityyadd;
    private javax.swing.JTextField cityydelete;
    private javax.swing.JTextField cityysearch;
    private javax.swing.JTextField cityyupdate;
    private javax.swing.JTextField dateadd;
    private javax.swing.JTextField datedelete;
    private javax.swing.JTextField datesearch;
    private javax.swing.JTextField dateupdate;
    private javax.swing.JTextField fnameadd;
    private javax.swing.JTextField fnamedelete;
    private javax.swing.JTextField fnamesearch;
    private javax.swing.JTextField fnameupdate;
    private javax.swing.JComboBox<String> genadd;
    private javax.swing.JComboBox<String> gendelete;
    private javax.swing.JComboBox<String> gensearch;
    private javax.swing.JComboBox<String> genupdate;
    private javax.swing.JTextField idadd;
    private javax.swing.JTextField iddelete;
    private javax.swing.JTextField idsearch;
    private javax.swing.JTextField idupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField joinadd;
    private javax.swing.JTextField joindelete;
    private javax.swing.JTextField joinsearch;
    private javax.swing.JTextField joinupdate;
    private javax.swing.JTextField phonenoadd;
    private javax.swing.JTextField phonenodelete;
    private javax.swing.JTextField phonenosearch;
    private javax.swing.JTextField phonenoupdate;
    private javax.swing.JTable receptable;
    private javax.swing.JComboBox<String> relationadd;
    private javax.swing.JComboBox<String> relationdelete;
    private javax.swing.JComboBox<String> relationsearch;
    private javax.swing.JComboBox<String> relationupdate;
    private javax.swing.JTextField snameadd;
    private javax.swing.JTextField snamedelete;
    private javax.swing.JTextField snamesearch;
    private javax.swing.JTextField snameupdate;
    // End of variables declaration//GEN-END:variables
}
